- name: conditions
  hosts: localhost
  tasks:
    - name: print veggies
      ansible.builtin.debug:
        msg: fruits and veggies
      when: true | bool

    - name: print nonveg
      ansible.builtin.debug:
        msg: all meat
      when: false | bool


