- name: conditions
  hosts: all
  tasks:
    - name: print veggies
      ansible.builtin.debug:
        msg: fruits and veggies
      tags: "veg"

    - name: print nonveg
      ansible.builtin.debug:
        msg: all meat
      tags: "nonveg"


