- name: conditions
  hosts: localhost
  tasks:
    - name: print veggies
      ansible.builtin.debug:
        msg: fruits and veggies
      when: option == "veg"

    - name: print nonveg
      ansible.builtin.debug:
        msg: all meat
      when: option == "nonveg"


